version: '2'
services:
  gideone-testcase-db:
    image: "postgres:16.0-bookworm"
    container_name: gideone-testcase-db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - gideone-testcase-network
    healthcheck:
      test: [
        "CMD",
        "pg_isready",
        "--host=127.0.0.1",
        "--username=postgres",
        "--port=5432"
      ]
      interval: 10s
      timeout: 30ms
      retries: 3
      start_period: 15s
      start_interval: 1s

  gideone-testcase-server:
    build: ./server
    image: gideone-testcase-server
    container_name: gideone-testcase-server
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on:
      gideone-testcase-db:
        condition: service_healthy
        restart: true
    restart: on-failure
    ports:
      - "127.0.0.1:8000:80"
    networks:
      - gideone-testcase-network
    healthcheck:
      test: [
        "CMD",
        "curl",
        "127.0.0.1:80/",
      ]
      interval: 10s
      timeout: 30ms
      retries: 3
      start_period: 15s
      start_interval: 1s

  gideone-testcase-client:
    build: ./client
    image: gideone-testcase-client
    container_name: gideone-testcase-client
    depends_on:
      gideone-testcase-server:
        condition: service_healthy
    networks:
      - gideone-testcase-network

networks:
  gideone-testcase-network:
    name: gideone-testcase-network
